app/views/layouts/application.html.erb
=> Matsuda feature model cartitem/order/orderdetail

app/views/layouts/application.html.erb
application.htmlの１行目matsudaを削除しました。
=> second commit

app/models/address.rb, app/models/genre.rb, app/models/item.rb, db/migrate/20241117015030_create_addresses.rb, db/migrate/20241117020337_create_items.rb, db/migrate/20241117020518_create_genres.rb, db/schema.rb, test/fixtures/addresses.yml, test/fixtures/genres.yml, test/fixtures/items.yml, test/models/address_test.rb, test/models/genre_test.rb, test/models/item_test.rb
test/fixtures/adresses.ymlのpost_codeをpostal_codeへ変更しました
=> Onuki feature model adress/item/genre

db/migrate/20241116071128_create_orders.rb, db/migrate/20241116090058_create_order_details.rb, db/migrate/20241119045935_add_name_to_cart_items.rb, db/schema.rb
cart_item amountカラム追加　orderのstatus,order_detailのmaking_status初期値追加
=> [add]cart_item amountカラム追加　orderのstatus,order_detailのmaking_status初期値追加

db/migrate/20241119045935_add_name_to_cart_items.rb, db/schema.rb
=> [add]cart_item null:false 追加

app/assets/stylesheets/public/cart_items.scss, app/controllers/public/cart_items_controller.rb, app/helpers/public/cart_items_helper.rb, app/views/public/cart_items/index.html.erb, config/routes.rb, test/controllers/public/cart_items_controller_test.rb
cart_itemコントローラー追加　メソッドのみ、ビュー作成
=> Matsuda feature controller public/cart items

app/models/address.rb, app/models/cart_item.rb, app/models/customer.rb, app/models/genre.rb, app/models/item.rb, app/models/order.rb, app/models/order_detail.rb
=>  [Add]アソシエーション設定(修正ずみ)

app/models/genre.rb
- cart_itemsになっていたのでitemsに変更しました
=> [Add]アソシエーション設定(修正)

app/assets/stylesheets/admin/order_details.scss, app/controllers/admin/order_details_controller.rb, app/helpers/admin/order_details_helper.rb, config/routes.rb, test/controllers/admin/order_details_controller_test.rb
admin/order_detailsコントローラー、ルーティング作成、メソッド名のみ記述。
=> [add]admin/order_detailsコントローラー、メソッド、ルーティング作成

app/controllers/admin/items_controller.rb, app/models/item.rb, app/views/admin/items/new.html.erb
商品新規投稿機能を実装しました!
備考
商品を投稿するためにはジャンルを登録する必要があるため、ジャンル登録機能の実施を急ぎます。
機能の確認はジャンル登録機能が実装できた後に可能になります。
=> [Add]商品新規投稿機能実装

config/application.rb, config/locales/devise.ja.yml, config/locales/ja.yml
enum導入後の記述をファイルに行いました。application.rbに日本語対応させるための記述。ja.ymlファイルを作成し、日本語訳追加。devise.ja.ymlファイルを作成し、devise関係の日本語訳追加。
=> [check]onuki-feature-function-public/newitemマージ前コミット

db/migrate/20241120140306_create_active_storage_tables.active_storage.rb, db/schema.rb
active storageを導入し、ブランチ名を修正しました。
=> [Add]active_storage導入

app/controllers/admin/items_controller.rb, app/views/admin/items/edit.html.erb, app/views/admin/items/show.html.erb
=> [Add]管理者側商品編集機能の実装

app/controllers/admin/genres_controller.rb, app/controllers/public/items_controller.rb, app/views/admin/genres/edit.html.erb, app/views/public/items/index.html.erb
=> Onuki feature function admin/editgenre

app/controllers/public/items_controller.rb, app/views/public/items/index.html.erb, config/initializers/kaminari_config.rb
顧客側の商品一覧ページを作成しました。(url: /items)
ページネーションも適用済みです!
(8件以上投稿しないとページネーション表示されません)
=> [Add]顧客側商品一覧画面実装

app/views/layouts/_header.html.erb, db/seeds.rb
- 管理者のログイン機能を統一しています
- メアド　admin@gmail.com
- パス　nagano_cake
=> [Add]管理者ログイン機能

app/models/item.rb, app/views/public/items/show.html.erb
item show カート追加個数選択フォーム 未入力で進めないようにバリデーション追加、フォームにも０で進めないようにコード記述。
=> [add]item show カート追加個数選択フォーム 未入力で進めないように変更

app/controllers/public/addresses_controller.rb, app/views/public/addresses/_form.html.erb, app/views/public/addresses/edit.html.erb, app/views/public/addresses/index.html.erb
=> Onuki feature function public/editraddress

app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb
=> Nagata feature fanction layouts/view

app/controllers/public/orders_controller.rb, config/routes.rb
=> [check]エラー確認　元の状態に戻しました

app/controllers/public/orders_controller.rb, app/views/public/customers/show.html.erb, app/views/public/orders/index.html.erb
-注文履歴一覧画面作成
-order indexアクション定義
-order コントローラーにbefore_actionのexceptにcomplete index show追加
- customer showページ　注文履歴見るボタンのパス変更
=> [add]注文履歴一覧画面

app/controllers/public/orders_controller.rb, app/views/public/orders/show.html.erb
=> [add]注文履歴詳細画面

app/controllers/admin/customers_controller.rb, app/controllers/admin/genres_controller.rb, app/controllers/admin/homes_controller.rb, app/controllers/admin/items_controller.rb, app/controllers/admin/order_details_controller.rb, app/controllers/admin/orders_controller.rb, app/controllers/admin/searches_controller.rb, app/controllers/public/addresses_controller.rb, app/controllers/public/cart_items_controller.rb, app/controllers/public/customers_controller.rb, app/controllers/public/orders_controller.rb, app/controllers/public/registrations_controller.rb, app/controllers/public/searches_controller.rb, app/controllers/public/sessions_controller.rb, app/views/public/customers/unsubscribe.html.erb, db/schema.rb
- ログインしていない時のアクセス制限の追加
- 退会した後の再入会の設定
=> Nagata feature function devise/limit

app/views/public/items/show.html.erb
-未ログインユーザーに対して、カート追加ができないようにボタンを非表示にしました。
=> [add]未ログインユーザーに対してカート追加ボタンを非表示にした

app/assets/stylesheets/application.css, app/controllers/admin/homes_controller.rb, app/views/admin/homes/index.erb, config/locales/ja.yml
-/adminの注文一覧画面を作成。
-カミナリのファイルに記述。次へボタンをnext>に、最後への部分をLast>に変更するコード
=> Matsuda feature function admin/orderindex

app/controllers/admin/orders_controller.rb, app/views/admin/orders/show.html.erb
- adminの注文履歴詳細画面を作成。更新ボタンはまだ押せない状態です。
=> Matsuda feature function admin/orderdetails

app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, app/views/public/customers/unsubscribe.html.erb
- p/show画面のレイアウト調整
- p/edit画面のレイアウト調整
- -p/unsubscribe画面のレイアウト調整
=> Nagata feature fanction p/customers/view

app/controllers/admin/order_details_controller.rb, app/controllers/admin/orders_controller.rb, app/controllers/public/cart_items_controller.rb
更新成功、失敗のフラッシュメッセージの実装
- 管理者
　- 注文ステータス変更時
　- 製作ステータス変更時
- 会員
- カートアイテム数量変更時
- カートアイテム１つ削除時
- カートアイテム全削除時
=> Matsuda feature function flashmessage

app/views/admin/customers/edit.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb, app/views/layouts/_customer_show.html.erb, app/views/public/customers/show.html.erb
- a/editレイアウト編集
- a/showレイアウト編集
- showの一部部分テンプレート化
=> Nagata feature fanction admin/customers/view

app/controllers/admin/orders_controller.rb, app/controllers/public/cart_items_controller.rb, app/views/public/cart_items/index.html.erb, app/views/public/orders/new.html.erb
- cart_item コントローラーの記述ミスを訂正
　- curretn_customerとの紐づけを追加。create,destroy,destroy_all,updateでのcart_item全てから見つけてしまう誤作動を解消す。
- レイアウト調整
　- cart_item index カート内アイテム表示画面
　- order new　注文確認の配送先選択画面
=> Matsuda feature function public/addtocart

app/controllers/public/orders_controller.rb, app/views/public/orders/check.html.erb, app/views/public/orders/new.html.erb
- orderコントローラーにcurrent_userを追加。違う顧客情報を見れないように変更。
- orderコントローラー　フラッシュメッセージ記述訂正
- order check 注文確認のページのレイアウト整えた
=> [change]orderコントローラー記述訂正 order check画面レイアウト訂正

app/views/public/homes/about.html.erb
aboutページ作成しました!
見づらかったら手加えてもOKです!
=> Onuki feature function public/aboutscreen

app/views/layouts/_header.html.erb
=> ロゴでトップページへ

app/views/public/orders/new.html.erb
- order new 注文確認前の配送先選択画面のレイアウト編集
　- bootstrap記述追加
　- プレースホルダー追加
=> Matsuda feature function public/orderinformation

app/controllers/public/items_controller.rb, app/views/kaminari/_first_page.html.erb, app/views/kaminari/_gap.html.erb, app/views/kaminari/_last_page.html.erb, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_paginator.html.erb, app/views/kaminari/_prev_page.html.erb, app/views/kaminari/default/_first_page.html.erb, app/views/kaminari/default/_gap.html.erb, app/views/kaminari/default/_last_page.html.erb, app/views/kaminari/default/_next_page.html.erb, app/views/kaminari/default/_page.html.erb, app/views/kaminari/default/_paginator.html.erb, app/views/kaminari/default/_prev_page.html.erb, app/views/public/items/index.html.erb
=> Onuki feature function public/itemindex

app/controllers/admin/orders_controller.rb
=> [error]発送済みを押すと出るエラー解決

app/controllers/public/orders_controller.rb
=> [change]注文履歴一覧を新しい順の並び順にした

app/helpers/admin/genres_helper.rb, app/helpers/admin/items_helper.rb, app/helpers/adresses_helper.rb, app/helpers/genres_helper.rb, app/helpers/items_helper.rb, app/helpers/public/adresses_helper.rb, app/helpers/public/items_helper.rb, app/views/admin/items/show.html.erb
=> Onuki feature function admin/itemshow

app/controllers/admin/items_controller.rb, app/views/admin/items/index.html.erb
=> Onuki feature function admin/itemindex

app/views/admin/items/index.html.erb
=> [Update]微修正

app/controllers/admin/genres_controller.rb, app/models/genre.rb, app/views/admin/genres/_form.html.erb, app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb
=> [Update]体裁整え

app/views/admin/genres/edit.html.erb
=> [Update]submitボタンの変更

app/javascript/stylesheets/application.scss, app/views/admin/genres/_form.html.erb, app/views/admin/items/_form.html.erb, app/views/admin/items/show.html.erb, app/views/public/homes/top.html.erb, app/views/public/items/index.html.erb, app/views/public/items/show.html.erb
=> [Add]画像を1:1にトリミング

app/views/public/genres/show.html.erb, app/views/public/searches/index.html.erb
- ジャンル検索結果をis_activeがtrueのもののみ表示するように設定
=> ジャンル検索結果画面の編集

app/javascript/stylesheets/application.scss, app/views/public/homes/top.html.erb, config/routes.rb
商品一覧ページへのリンクを作成しました。
買い物のサイトなので商品一覧が最も閲覧されるページです。
リンクは分かりやすい方が良いのでほんの少しだけ目立つようにしています。
=> [Add]商品一覧ページリンク作成

app/javascript/stylesheets/application.scss, app/views/layouts/application.html.erb
=> [Update]フッター位置調整

app/controllers/public/items_controller.rb, app/views/public/items/index.html.erb
=> [Update]全商品数をカウント

README.md
=> [Add]ReadMeファイルの記述

app/controllers/public/addresses_controller.rb, app/models/address.rb, app/models/customer.rb, app/views/public/customers/show.html.erb
不具合を修正しました。
・URLの不具合(mypage#editのURL修正)
・ユーザー情報の未入力防止バリデーション追加
・住所一覧画面の不具合修正
=> [Update]不具合修正
